---
sudo: false
before_script:
  - git clone https://github.com/exercism/problem-specifications.git
  - bin/fetch-configlet
  - docker pull rakudo-star:latest
script:
  - bin/configlet lint .
  - docker run
    --volume $PWD:/exercism
    rakudo-star /exercism/bin/rename-exercises.pl6
  - docker run
    --env EXERCISM=1
    --volume $PWD:/exercism
    rakudo-star prove /exercism
    --exec perl6
    --recurse
    --jobs 2
