---
sudo: required
services:
  - docker
before_script:
  - bin/fetch-configlet
  - docker pull rakudo-star:latest
script:
  - bin/configlet .
  - docker run -e EXERCISM=1 -t -v $PWD:/exercism rakudo-star prove /exercism -re perl6